version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run:
                name: Build
                command: |
                    npm ci
                    node_modules/.bin/vsce package --out vscode-ghc-simple.vsix
            - store_artifacts:
                path: vscode-ghc-simple.vsix
                destination: package
                